version: '2'

services:
  drone-server:
    container_name: drone
    image: drone/drone:1
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./data:/var/lib/dron/
    restart: always
    environment:
      - DRONE_GIT_ALWAYS_AUTH=false
      - DRONE_TLS_AUTOCERT=false
      - DRONE_GITHUB_SERVER=https://github.com
      - DRONE_GITHUB_CLIENT_ID= 87a522869f26d6f0e1ed
      - DRONE_GITHUB_CLIENT_SECRET= da6326c9570adcc60584d0a5edb7f104447f0fb0
      - DRONE_RUNNER_CAPACITY=2 
      - DRONE_SERVER_HOST=be45c1618f87.ngrok.io
      - DRONE_SERVER_PROTO=http