version: '3.7'

services:
  drone-server:
    container_name: drone_server
    image: drone/drone:1
    ports:
      - 80:80
    volumes:
      - /var/lib/drone:/data
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
    environment:
      - DRONE_GITHUB_SERVER=https://github.com
      - DRONE_GITHUB_CLIENT_ID=87a522869f26d6f0e1ed
      - DRONE_GITHUB_CLIENT_SECRET=da6326c9570adcc60584d0a5edb7f104447f0fb0
      - DRONE_AGENTS_ENABLED=true
      - DRONE_RPC_SECRET=da6326c9570adcc60584d0a5edb7f104447f0fb0
      - DRONE_SERVER_HOST=http://be45c1618f87.ngrok.io
      - DRONE_SERVER_PROTO=https
      - DRONE_TLS_AUTOCERT=true
      - DRONE_USER_CREATE=username:drsnitst,admin:true
      - DRONE_LOGS_TRACE=true
      - DRONE_LOGS_PRETTY=true
      - DRONE_LOGS_COLOR=true

  drone-agent:
    container_name: drone_agent
    image: drone/agent:1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
    environment:
      - DRONE_RPC_HOST=drone-server
      - DRONE_RPC_SECRET=da6326c9570adcc60584d0a5edb7f104447f0fb0
      - DRONE_RUNNER_CAPACITY=1
      - DRONE_RUNNER_NAME=testci
      - DRONE_LOGS_TRACE=true
      - DRONE_LOGS_PRETTY=true
      - DRONE_LOGS_COLOR=true